project:
  type: website

website:
  page-navigation: true
  site-url: "https://ronaldvisser.github.io/R_4_Archaeology/"
  repo-url: https://github.com/RonaldVisser/R_4_Archaeology/
  title: "R_4_Archaeology"
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By-NC Ronald Visser, Alex Brandsen & Anne Dijkstra 2025"
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: projects.qmd
        text: Projects in RStudio
      - href: libraries_data.qmd
        text: Importing Libraries and Data
      - href: join_statistics.qmd
        text: Joining Tables and Basic Statistics
      - href: plotting_data.qmd
        text: Plotting Data with ggplot
      - href: spatial_analysis.qmd
        text: Plotting Data with ggplot
      - about.qmd

format:
  html:
    theme:
      light: [theme]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - quarto

